version: '2'
services:
  payslip-app:
    image: payslip
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://payslip-mariadb:3306/payslip
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8088:8088
  payslip-mariadb:
    extends:
      file: mariadb.yml
      service: payslip-mariadb
